/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pb138.gui;

import cz.muni.fi.pb138.Devices.Device;
import cz.muni.fi.pb138.Devices.DeviceType;
import cz.muni.fi.pb138.Devices.Port;
import cz.muni.fi.pb138.gui.form.SelectForm;
import cz.muni.fi.pb138.gui.form.DeviceForm;
import cz.muni.fi.pb138.gui.form.PortForm;
import cz.muni.fi.pb138.gui.form.PortFormDelete;
import cz.muni.fi.pb138.gui.form.Spot;
import cz.muni.fi.pb138.Main.ListOfDevices;
import cz.muni.fi.pb138.Managers.DeviceManager;
import cz.muni.fi.pb138.Managers.DeviceManagerImpl;
import cz.muni.fi.pb138.Managers.PortManager;
import cz.muni.fi.pb138.Managers.PortManagerImpl;
import cz.muni.fi.pb138.Validation.Validator;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.SwingWorker;
import javax.swing.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.Collections;
import cz.muni.fi.pb138.gui.form.utils.LineDrawer;
import java.awt.Color;
import java.awt.Point;
import java.io.IOException;
import org.xml.sax.SAXException;

/**
 *
 * @author Magdalena Kunikova
 */
public class Main extends javax.swing.JFrame {

    private static ListOfDevices listOfDevices = new ListOfDevices();
    private static DeviceManager deviceManager = new DeviceManagerImpl(listOfDevices);
    private static PortManager portManager = new PortManagerImpl();
    private static LineDrawer linker;
    
    private DeviceForm deviceForm;
    private List<Device> devices;
    public final int REMOVE = 0;
    public final int ADD = 1;
    public final int EDIT = 2;
    private Port port;
    private int spot;
    private String name;
    private String address;
    private int numberOfPorts;
    private DeviceType deviceType;
    private static List<Spot> spots = new ArrayList<>();
    
    

    public Main() {
        //deviceManager = new DeviceManagerImpl();
        //portManager = new PortManagerImpl();
        
        devices = deviceManager.listAllDevices();
        linker = new LineDrawer();
        setGlassPane( linker );
        linker.setVisible( true );
                
        
        initComponents();
        setLocationRelativeTo(null);
        
        /*
        deviceForm.addWindowListener( new WindowAdapter() { 
            @Override
            public void windowClosed(WindowEvent we) {
                spot = deviceForm.getSpot();
                deviceType = deviceForm.getDeviceType();
                name = deviceForm.getName();
                address = deviceForm.getAddress();
                numberOfPorts = deviceForm.getNumberOfPorts();
                editLabel(name, deviceType, spot);
            }
        } );*/
    }

    public static DeviceManager getDeviceManager() {
        return deviceManager;
    }
    
    public static PortManager getPortManager() {
        return portManager;
    }
    
    public static LineDrawer getLinker() {
        return linker;
    }
    
    public static List<Spot> getSpots() {
        return Collections.unmodifiableList(spots);
    }
    
    public static Spot getSpotForDevice(Device device) {
        for (Spot s : spots) {
            if (s.getDevice() != null && 
                    s.getDevice().getAddress().equals(device.getAddress())) {
                return s;
            }
        }
        
        return null;
    }
    
    private Point getLabelCenter(JLabel label) {
        Point location = label.getLocation();
        Dimension size = label.getSize();
        
        return new Point(location.x + size.width / 2, location.y + size.height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAddDevice = new javax.swing.JButton();
        buttonAddPort = new javax.swing.JButton();
        buttonDeletePort = new javax.swing.JButton();
        labelDevice = new javax.swing.JLabel();
        labelPort = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        labelSpot1 = new javax.swing.JLabel();
        labelSpot2 = new javax.swing.JLabel();
        labelSpot3 = new javax.swing.JLabel();
        labelSpot4 = new javax.swing.JLabel();
        labelSpot5 = new javax.swing.JLabel();
        labelSpot6 = new javax.swing.JLabel();
        labelSpot7 = new javax.swing.JLabel();
        labelSpot8 = new javax.swing.JLabel();
        labelSpot9 = new javax.swing.JLabel();
        labelSpot10 = new javax.swing.JLabel();
        labelSpot11 = new javax.swing.JLabel();
        labelSpot12 = new javax.swing.JLabel();
        labelSpot13 = new javax.swing.JLabel();
        labelSpot14 = new javax.swing.JLabel();
        labelSpot15 = new javax.swing.JLabel();
        labelSpot16 = new javax.swing.JLabel();
        labelSpot17 = new javax.swing.JLabel();
        labelSpot18 = new javax.swing.JLabel();
        labelSpot19 = new javax.swing.JLabel();
        labelSpot20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        importButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Map of network");

        buttonAddDevice.setText("Add device");
        buttonAddDevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddDeviceActionPerformed(evt);
            }
        });

        buttonAddPort.setText("Add port");
        buttonAddPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddPortActionPerformed(evt);
            }
        });

        buttonDeletePort.setText("Delete port");
        buttonDeletePort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeletePortActionPerformed(evt);
            }
        });

        labelDevice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelDevice.setText("Device");

        labelPort.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPort.setText("Port");

        panelContent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Spot spot1 = new Spot(1, labelSpot1, null);
        spots.add(spot1);
        labelSpot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot1.setText("Spot 1");
        labelSpot1.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot1.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot1);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot2 = new Spot(2, labelSpot2, null);
        spots.add(spot2);
        labelSpot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot2.setText("Spot 2");
        labelSpot2.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot2.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot2);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot3 = new Spot(3, labelSpot3, null);
        spots.add(spot3);
        labelSpot3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot3.setText("Spot 3");
        labelSpot3.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot3.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot3);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot4 = new Spot(4, labelSpot4, null);
        spots.add(spot4);
        labelSpot4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot4.setText("Spot 4");
        labelSpot4.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot4.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot4);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot5 = new Spot(5, labelSpot5, null);
        spots.add(spot5);
        labelSpot5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot5.setText("Spot 5");
        labelSpot5.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot5.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot5);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot6 = new Spot(6, labelSpot6, null);
        spots.add(spot6);
        labelSpot6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot6.setText("Spot 6");
        labelSpot6.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot6.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot6);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot7 = new Spot(7, labelSpot7, null);
        spots.add(spot7);
        labelSpot7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot7.setText("Spot 7");
        labelSpot7.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot7.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot7);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot8 = new Spot(8, labelSpot8, null);
        spots.add(spot8);
        labelSpot8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot8.setText("Spot 8");
        labelSpot8.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot8.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot8);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot9 = new Spot(9, labelSpot9, null);
        spots.add(spot9);
        labelSpot9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot9.setText("Spot 9");
        labelSpot9.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot9.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot9);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot10 = new Spot(10, labelSpot10, null);
        spots.add(spot10);
        labelSpot10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot10.setText("Spot 10");
        labelSpot10.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot10.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot10);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot11 = new Spot(11, labelSpot11, null);
        spots.add(spot11);
        labelSpot11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot11.setText("Spot 11");
        labelSpot11.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot11.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot11);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot12 = new Spot(12, labelSpot12, null);
        spots.add(spot12);
        labelSpot12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot12.setText("Spot 12");
        labelSpot12.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot12.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot12);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot13 = new Spot(13, labelSpot13, null);
        spots.add(spot13);
        labelSpot13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot13.setText("Spot 13");
        labelSpot13.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot13.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot13);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot14 = new Spot(14, labelSpot14, null);
        spots.add(spot14);
        labelSpot14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot14.setText("Spot 14");
        labelSpot14.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot14.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot14);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot15 = new Spot(15, labelSpot15, null);
        spots.add(spot15);
        labelSpot15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot15.setText("Spot 15");
        labelSpot15.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot15.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot15);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot16 = new Spot(16, labelSpot16, null);
        spots.add(spot16);
        labelSpot16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot16.setText("Spot 16");
        labelSpot16.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot16.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot16);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot17 = new Spot(17, labelSpot17, null);
        spots.add(spot17);
        labelSpot17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot17.setText("Spot 17");
        labelSpot17.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot17.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot17);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot18 = new Spot(18, labelSpot18, null);
        spots.add(spot18);
        labelSpot18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot18.setText("Spot 18");
        labelSpot18.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot18.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot18);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot19 = new Spot(19, labelSpot19, null);
        spots.add(spot19);
        labelSpot19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot19.setText("Spot 19");
        labelSpot19.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot19.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot19);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Spot spot20 = new Spot(20, labelSpot20, null);
        spots.add(spot20);
        labelSpot20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpot20.setText("Spot 20");
        labelSpot20.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent arg0) {
                if(labelSpot20.getText().equals("")) {
                    SelectForm selectForm = new SelectForm(spot20);
                    selectForm.setLocationRelativeTo(null);
                    selectForm.setVisible(true);
                }
            }

            @Override
            public void mouseExited(MouseEvent arg0) {
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
            }

            @Override
            public void mousePressed(MouseEvent arg0) {
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
            }
        });
        labelSpot20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelContentLayout.createSequentialGroup()
                        .addComponent(labelSpot16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(labelSpot17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(labelSpot18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(labelSpot19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(labelSpot20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelContentLayout.createSequentialGroup()
                            .addComponent(labelSpot11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(labelSpot12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(labelSpot13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(labelSpot14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(labelSpot15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelContentLayout.createSequentialGroup()
                                .addComponent(labelSpot6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(labelSpot7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(labelSpot8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(labelSpot9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(labelSpot10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelContentLayout.createSequentialGroup()
                                .addComponent(labelSpot1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(labelSpot2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(labelSpot3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(labelSpot4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(labelSpot5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSpot1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpot3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpot2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpot4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpot5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSpot6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpot8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpot7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpot9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpot10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSpot11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpot13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpot12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpot14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpot15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSpot16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpot18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpot17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpot19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpot20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("File");

        importButton.setLabel("Import");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        exportButton.setLabel("Export");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPort)
                    .addComponent(labelDevice)
                    .addComponent(buttonAddPort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAddDevice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDeletePort, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(importButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labelDevice)
                .addGap(18, 18, 18)
                .addComponent(buttonAddDevice)
                .addGap(35, 35, 35)
                .addComponent(labelPort)
                .addGap(18, 18, 18)
                .addComponent(buttonAddPort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonDeletePort)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(importButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exportButton)
                .addGap(45, 45, 45)
                .addComponent(exitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddDeviceActionPerformed
        deviceForm = new DeviceForm();
        deviceForm.setVisible(true);
    }//GEN-LAST:event_buttonAddDeviceActionPerformed

    private void buttonAddPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddPortActionPerformed
        if (devices.size() < 2){
            JOptionPane.showMessageDialog(rootPane, "Create at least two devices to add a port.");
            return;
        }
        
        PortForm portForm = new PortForm();
        portForm.setVisible(true);
    }//GEN-LAST:event_buttonAddPortActionPerformed

    private void buttonDeletePortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeletePortActionPerformed
        PortFormDelete deleteForm = new PortFormDelete();
        
        deleteForm.setLocationRelativeTo(null);
        deleteForm.setVisible(true);
    }//GEN-LAST:event_buttonDeletePortActionPerformed

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        // Import file
        try {
            Validator validation = new Validator(new String[] {"resultfile.xml", "masterrouter.xsd"});
            listOfDevices.importXML("./resultfile.xml");
        }
        catch (IOException ioe) {
            JOptionPane.showMessageDialog(null, "Unable to import the file.");
            return;
        }
        catch (SAXException saxe) {
            JOptionPane.showMessageDialog(null, "Imported file is not valid.");
            saxe.printStackTrace();
            return;
        }
        
        // Load into JLabels
        // Delete redundant devices
        List<Device> listOfLoadedDevices = listOfDevices.getListOfDevices();
        if (listOfLoadedDevices.size() > 20) {
            JOptionPane.showMessageDialog(null, "Too many devices to display. All devices above 20 will not be considered.");
            
            System.out.println("Size before: " + listOfLoadedDevices.size());
            // Delete devices ports
            for (int i = 19; i < listOfLoadedDevices.size(); i++) {
                listOfLoadedDevices.get(i).setNumberOfPorts(0);
            }
            
            // Trim device list
            listOfLoadedDevices.removeIf(device -> listOfLoadedDevices.indexOf(device) >= 20);
            System.out.println("Size after: " + listOfLoadedDevices.size());
        }
        
        // Display remaining devices
        for (int i = 0; i < listOfLoadedDevices.size(); i++) {
            //Main.getSpots().get(spot - 1).updateSpot(newDevice);
            spots.get(i).updateSpot(listOfLoadedDevices.get(i));
        }
            
        // Link existing ports
        for (int i = 0; i < listOfLoadedDevices.size(); i++) {
            List<Port> listOfAllDevicePorts = portManager.listAllPortsOfDevice(listOfLoadedDevices.get(i));
                
            for (Port port : listOfAllDevicePorts) {
                Spot spotA = getSpotForDevice(port.getDeviceA());
                Spot spotB = getSpotForDevice(port.getDeviceB());
            
                linker.link(port, getLabelCenter(spotA.getLabel()), 
                    getLabelCenter(spotB.getLabel()), Color.RED);
                
                System.out.println("Port hashcode: " + port.hashCode());
            }
        }
    }//GEN-LAST:event_importButtonActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        listOfDevices.exportXML();
        JOptionPane.showMessageDialog(null, "File exported.");
        
        try {
            Validator validation = new Validator(new String[] {"resultfile.xml", "masterrouter.xsd"});
        }
        catch (IOException ioe) {
            JOptionPane.showMessageDialog(null, "Unable to validate the file.");
        }
        catch (SAXException saxe) {
            JOptionPane.showMessageDialog(null, "Created file is not valid.");
        }
    }//GEN-LAST:event_exportButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddDevice;
    private javax.swing.JButton buttonAddPort;
    private javax.swing.JButton buttonDeletePort;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exportButton;
    private javax.swing.JButton importButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDevice;
    private javax.swing.JLabel labelPort;
    private javax.swing.JLabel labelSpot1;
    private javax.swing.JLabel labelSpot10;
    private javax.swing.JLabel labelSpot11;
    private javax.swing.JLabel labelSpot12;
    private javax.swing.JLabel labelSpot13;
    private javax.swing.JLabel labelSpot14;
    private javax.swing.JLabel labelSpot15;
    private javax.swing.JLabel labelSpot16;
    private javax.swing.JLabel labelSpot17;
    private javax.swing.JLabel labelSpot18;
    private javax.swing.JLabel labelSpot19;
    private javax.swing.JLabel labelSpot2;
    private javax.swing.JLabel labelSpot20;
    private javax.swing.JLabel labelSpot3;
    private javax.swing.JLabel labelSpot4;
    private javax.swing.JLabel labelSpot5;
    private javax.swing.JLabel labelSpot6;
    private javax.swing.JLabel labelSpot7;
    private javax.swing.JLabel labelSpot8;
    private javax.swing.JLabel labelSpot9;
    private javax.swing.JPanel panelContent;
    // End of variables declaration//GEN-END:variables
}
